### PR TITLE
updated Readme and User Guide

### PR DESCRIPTION
**Pull request by ghego**
Hey @ZhengyaoJiang I've updated the readme and user guide to reflect the current version of the library. Please have a look and let me know if I missed anything or if there are other things that need improvement.

I mostly simplified the explanation and made it clearer where I thought there were ambiguities.

### CODE REVIEW

**Comment by ghego** [comment]
I've also fixed a bug that would crash the plotting function if no display was found and updated the required packages

**Comment by DexHunter** [comment]
@ghego Thanks for the PR. Although we did convert most algorithms from matlab to python for OLPS, it is not our intention to highlight the traditional algorithms but rather our drl approach. So I don't think it's necessary to add so many explanations for traditional algorithms. But still, thanks for the PR.

**Comment by ghego** [comment]
Understood. I ended up adding a few more changes to clean up the code as well. I think it's important to have a bit of information about the other algos. maybe I can move it to a different Readme file inside the traditional algo folder?

**Comment by DexHunter** [comment]
>  maybe I can move it to a different Readme file inside the traditional algo folder?

**Comment by ghego** [comment]
done. moved explanation to separate readme

**Comment by ZhengyaoJiang** [comment]
Thanks for your contribution.

**Pull request merged**
